services:
  database:
    image: postgres
    container_name: 'url-shortener-database'
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/data/postgres
    restart: always

  api:
    build: .
    container_name: 'url-shortener-api'
    restart: always
    env_file: .env
    working_dir: /usr/app/src
    expose:
      - '3000'
    environment:
      - APP_PORT=3000
      - DB_HOST=database
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
